CREATE TABLE IF NOT EXISTS  T_USER(
   ID INT NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(100) NOT NULL,
   AGE INT NOT NULL,
   ADDR VARCHAR(200),
   PRIMARY KEY ( ID )
);


--INSERT INTO T_USER (NAME, AGE, ADDR) VALUES ('Jack', 20, 'BJ');
--INSERT INTO T_USER (NAME, AGE, ADDR) VALUES ('Jones', 18, 'SH');